apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: yunikorn-dev
  namespace: flux-system
spec:
  interval: 5m
  path: ./infrastructure/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: yunikorn-multi-env
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: yunikorn-dev
      namespace: yunikorn-dev
  timeout: 10m
