apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: yunikorn-multi-env
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/enricay/yunikorn-multi-env
