apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: yunikorn-scheduler-pdb
  namespace: yunikorn-prod
  labels:
    app.kubernetes.io/name: yunikorn
    app.kubernetes.io/component: scheduler
    environment: production
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: yunikorn
      component: yunikorn-scheduler
      environment: production
