apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: yunikorn-staging

# Use base configuration
resources:
  - ../base

# Add environment-specific labels
commonLabels:
  environment: staging
  app.kubernetes.io/instance: yunikorn-staging

# Namespace suffix for staging
nameSuffix: -staging

# Environment-specific patches
patches:
  # Update namespace name to yunikorn-staging
  - target:
      kind: Namespace
      name: yunikorn
    patch: |-
      - op: replace
        path: /metadata/name
        value: yunikorn-staging
  # Moderate resources for staging environment
  - target:
      kind: HelmRelease
      name: yunikorn
    patch: |-
      - op: replace
        path: /spec/values/resources/limits/cpu
        value: "1000m"
      - op: replace
        path: /spec/values/resources/limits/memory
        value: "1Gi"
      - op: replace
        path: /spec/values/resources/requests/cpu
        value: "200m"
      - op: replace
        path: /spec/values/resources/requests/memory
        value: "256Mi"
      - op: replace
        path: /spec/values/web/resources/limits/cpu
        value: "500m"
      - op: replace
        path: /spec/values/web/resources/limits/memory
        value: "512Mi"
      - op: replace
        path: /spec/values/web/resources/requests/cpu
        value: "100m"
      - op: replace
        path: /spec/values/web/resources/requests/memory
        value: "256Mi"
      - op: replace
        path: /spec/values/goMemoryLimit
        value: "512MiB"
  
  # Update namespace name
  - target:
      kind: HelmRelease
      name: yunikorn
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: yunikorn-staging
      
  # Add staging-specific labels
  - target:
      kind: HelmRelease
      name: yunikorn
    patch: |-
      - op: add
        path: /spec/values/podLabels/environment
        value: "staging"
  
  # Update PodDisruptionBudget for staging namespace
  - target:
      kind: PodDisruptionBudget
      name: yunikorn-scheduler-pdb
    path: pdb-patch.yaml
